export const GET_PERSONS = 'GET_PERSONS';
export const GET_ALLPERSONS = 'GET_ALLPERSON';
export const ADD_LIKES = 'ADD_LIKES';
export const REMOVE_LIKES = 'REMOVE_LIKES';
export const GET_PERSONSBYNAME = 'GET_PERSONSBYNAME';
export const SET_PERSONSBYNAME = 'SET_PERSONSBYNAME';
